### ISSUE TITLE
Change colouring of #define's

### ISSUE THREAD

**Issue by vojthas98** [Southclaws/pawn-sublime-language#61]
Thats more of an request than an issue, couldn't find any other way to contact as Southclaw's email isnt working.
I'd love to change the way macros used in code are coloured, currently they are white for me and I use them a lot in my gamemode and now they blend in with normal variables and stuff, previously I used some other Pawn syntax and it was colouring all defines (even custom ones), but it had problems with character escaping and it caused to color my entire code so I moved on to this one, and it's much better although I'd like to make my macros coloured again.
Somehow I have managed to get #define MACRO working, MACRO is coloured with different colour, but when it's used somewhere in the code it's still white. I'd be glad if someone would help me or point me a way I could get that to work.
I have attached an image showing my problem. I  want both of these in same (green, or different) colour.
![asd](https://cloud.githubusercontent.com/assets/28164600/25685575/c8d54658-3068-11e7-8b0b-3e5408f72a45.png)
Thanks in advance!

**Comment by Jessyy** [comment]
hey, can tell me what "Pawn syntax" did you used to color your "defines" in game-mode "when it's used somewhere in the code" ?

**Comment by Southclaws** [comment]
This could be as simple as just colouring all uppercase words.

**Comment by Jessyy** [comment]
please let this be the last solution to fix this issue
let's see what code has used @vojthas98 you will never know maybe has something more smarter then this

**Comment by Southclaws** [comment]
Constants are generally all uppercase in most naming conventions. There's no way to differentiate between an enumerated label, a constant and a definition without context of the entire codebase (not really in the scope of TM syntax). It wouldn't matter too much but I think it's something that warrants consideration before a major change.

**Comment by vojthas98** [comment]
Yeah it was just about coloring all uppercase, also in enums (but not lower case or anything with some letter being lowercase)
There is also some list of constants but if I recall correctly it was colouring every uppercase word, although it was very basic and had lots of bugs (the most annoying being not detecting character escapes like \" and causing the entire code to be coloured as text)
https://pastebin.com/20Knzdgx
I was messing with it a very long time ago and added some custom definitions but didn't do anything since then.
What would be the code to color the uppercase words? I'm not familiar with the way sublime's syntax colouring works. It would need to ignore characters like ( ) etc like when using Streamer_GetMaxItems(STREAMER_TYPE_OBJECT) only STREAMER_TYPE_OBJECT would be coloured. The above syntax colouring was failing with this if i recall correctly and you needed to put spaces before and after the word.
Also what I discovered is that using a single % sign (for example in dialogs) causes it's foreground to be marked (marking an mistake/error I guess) although it's only an error when formatting text but I guess it's just a cosmetical problem, luckily it colours only the % sign and not the entire code :D

**Comment by Southclaws** [comment]
The syntax works by using regular expressions and rules to mark nested sections. These sections are then given a scope name, you can see the name of some text by pressing ctrl+shift+alt+p. Colouring these constants should be simple, the regex would match something like `[A-Z0-9_@]` (off the top of my head) and the name would likely be something from section 12.4 of this list: http://manual.macromates.com/en/language_grammars

**Comment by vojthas98** [comment]
Got it working, just added another pattern match to lex-constant: (\b[A-Z0-9_@]+\b) and it works like a charm

**Comment by Southclaws** [comment]
Could you contribute via a pull request or simply post your modification here so others could benefit?
